// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1IbeB3sy506J3Mw6IL42ha7rxbTVECR4',
    appId: '1:26686543409:web:fc593bca2b010ddd4e6710',
    messagingSenderId: '26686543409',
    projectId: 'bmi-calculator-619b2',
    authDomain: 'bmi-calculator-619b2.firebaseapp.com',
    storageBucket: 'bmi-calculator-619b2.appspot.com',
    measurementId: 'G-BY76DJLX4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHtXKynjOSnrT-8jHKmv7CCmGxTxlr_Y',
    appId: '1:26686543409:android:050bb5d6ec6237c64e6710',
    messagingSenderId: '26686543409',
    projectId: 'bmi-calculator-619b2',
    storageBucket: 'bmi-calculator-619b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxIfV_KNHDfzqLJ6Xf6q9slQzcoVvDzYs',
    appId: '1:26686543409:ios:209927bc552c269e4e6710',
    messagingSenderId: '26686543409',
    projectId: 'bmi-calculator-619b2',
    storageBucket: 'bmi-calculator-619b2.appspot.com',
    iosBundleId: 'com.example.task11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxIfV_KNHDfzqLJ6Xf6q9slQzcoVvDzYs',
    appId: '1:26686543409:ios:209927bc552c269e4e6710',
    messagingSenderId: '26686543409',
    projectId: 'bmi-calculator-619b2',
    storageBucket: 'bmi-calculator-619b2.appspot.com',
    iosBundleId: 'com.example.task11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1IbeB3sy506J3Mw6IL42ha7rxbTVECR4',
    appId: '1:26686543409:web:3738fe1206e61d484e6710',
    messagingSenderId: '26686543409',
    projectId: 'bmi-calculator-619b2',
    authDomain: 'bmi-calculator-619b2.firebaseapp.com',
    storageBucket: 'bmi-calculator-619b2.appspot.com',
    measurementId: 'G-TSEG9WWF5E',
  );
}
